### ISSUE TITLE
clone and run doesn't work

### ISSUE THREAD

**Issue by hannesa2** [lotaviods/mqtt_example#1]
Hi, I was forced to do some changes
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/3314607/217005547-54e1b962-ce0a-48fa-a01d-2e0049f255be.png">

and 

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/3314607/217005622-c3d2cb9f-184f-4821-b540-d8eca6bf8658.png">

but when I start, 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/3314607/217005878-3fd0a7aa-e046-4a82-9a32-ac857a99d3bc.png">

I run into 
<img width="907" alt="image" src="https://user-images.githubusercontent.com/3314607/217005964-fd11ff02-11cf-4fd5-a8af-05c7da1ed96b.png">

To be honest, I'm tiered to put afford in a reproduce sample to see an issue. 

Please help me, to make a clone, run, show example ! **Thanks a lot !**

**Comment by lotaviods** [comment]
no problem, so can you have a url that matches tcp:// or ws:// scheme?

**Comment by lotaviods** [comment]
and please add port too

should be something like that: tcp://broker.hibemq.com:8884

**Comment by hannesa2** [comment]
please can you push your suggestions

**Comment by hannesa2** [comment]
Please commit your suggestion, to have a working build and a failing demo.

My stuff doesn't work. Nothing happens ....
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/3314607/217018353-43354d95-de4b-4179-ba17-b86717521c22.png">

<img width="921" alt="image" src="https://user-images.githubusercontent.com/3314607/217018633-b8cf7fb9-bf47-4d61-99a6-156ff7af7c92.png">

**Comment by lotaviods** [comment]
Your mqtt broker seems to not accepting connections

**Comment by hannesa2** [comment]
It's the broker from Espresso tests. 
<img width="758" alt="image" src="https://user-images.githubusercontent.com/3314607/217025191-d55722e4-7d34-4662-8331-677acfb73a83.png">

But I see, the protocol is different.
This is the reason why I ask for a running example. This endless ping pong about why stuff is not working as expected.

**Comment by hannesa2** [comment]
With `tcp://broker.hivemq.com:1883` I see now the crash !
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/3314607/217027078-975c92d2-b13a-4d47-99dc-1bb8b55937f0.png">

**Comment by hannesa2** [comment]
Hmm, why it doesn't find the constructor ?

<img width="954" alt="image" src="https://user-images.githubusercontent.com/3314607/217031071-9b6a51b6-a5ec-426f-8114-b74e40c28ed7.png">

> info.mqtt.android.service.ping.AlarmPingSender$PingWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]

The constructor is here 
![image](https://user-images.githubusercontent.com/3314607/217031412-4ae8abb8-ca6a-4ed5-a421-b35f884f3165.png)

**Comment by hannesa2** [comment]
<html><head></head><body>

`3.6.0-beta6` looks different now. At least no crash ! Please give it a try

I'm not sure about this `Task was cancelled`

</body></html>

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/3314607/217042372-44d7ac09-0f14-4ac6-8a28-01e37d554793.png">
